// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/:workspaceId": {
    params: {
      "workspaceId": string;
    };
  };
  "/dashboard/custom-domains": {
    params: {};
  };
  "/dashboard/submissions/:formId": {
    params: {
      "formId": string;
    };
  };
  "/dashboard/analytics/:formId": {
    params: {
      "formId": string;
    };
  };
  "/dashboard/integrations/:formId": {
    params: {
      "formId": string;
    };
  };
  "/dashboard/embed/:formId": {
    params: {
      "formId": string;
    };
  };
  "/dashboard/settings/:formId": {
    params: {
      "formId": string;
    };
  };
  "/:formId/edit": {
    params: {
      "formId": string;
    };
  };
  "/preview": {
    params: {};
  };
  "/:formId": {
    params: {
      "formId": string;
    };
  };
  "/:formId/verify": {
    params: {
      "formId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/dashboard" | "/dashboard/:workspaceId" | "/dashboard/custom-domains" | "/dashboard/submissions/:formId" | "/dashboard/analytics/:formId" | "/dashboard/integrations/:formId" | "/dashboard/embed/:formId" | "/dashboard/settings/:formId" | "/:formId/edit" | "/preview" | "/:formId" | "/:formId/verify";
  };
  "features/marketing/page.tsx": {
    id: "features/marketing/page";
    page: "/";
  };
  "features/auth/page.tsx": {
    id: "features/auth/page";
    page: "/auth";
  };
  "features/auth/protected.tsx": {
    id: "features/auth/protected";
    page: "/dashboard" | "/dashboard/:workspaceId" | "/dashboard/custom-domains" | "/dashboard/submissions/:formId" | "/dashboard/analytics/:formId" | "/dashboard/integrations/:formId" | "/dashboard/embed/:formId" | "/dashboard/settings/:formId" | "/:formId/edit" | "/preview";
  };
  "features/dashboard/route.tsx": {
    id: "features/dashboard/route";
    page: "/dashboard" | "/dashboard/:workspaceId" | "/dashboard/custom-domains" | "/dashboard/submissions/:formId" | "/dashboard/analytics/:formId" | "/dashboard/integrations/:formId" | "/dashboard/embed/:formId" | "/dashboard/settings/:formId";
  };
  "features/dashboard/page.tsx": {
    id: "features/dashboard/page";
    page: "/dashboard";
  };
  "features/workspace/route.tsx": {
    id: "features/workspace/route";
    page: "/dashboard/:workspaceId";
  };
  "features/workspace/page.tsx": {
    id: "features/workspace/page";
    page: "/dashboard/:workspaceId";
  };
  "features/custom-domain/route.tsx": {
    id: "features/custom-domain/route";
    page: "/dashboard/custom-domains";
  };
  "features/custom-domain/page.tsx": {
    id: "features/custom-domain/page";
    page: "/dashboard/custom-domains";
  };
  "features/form-manage/route.tsx": {
    id: "features/form-manage/route";
    page: "/dashboard/submissions/:formId" | "/dashboard/analytics/:formId" | "/dashboard/integrations/:formId" | "/dashboard/embed/:formId" | "/dashboard/settings/:formId";
  };
  "features/submissions/page.tsx": {
    id: "features/submissions/page";
    page: "/dashboard/submissions/:formId";
  };
  "features/analytics/page.tsx": {
    id: "features/analytics/page";
    page: "/dashboard/analytics/:formId";
  };
  "features/integrations/page.tsx": {
    id: "features/integrations/page";
    page: "/dashboard/integrations/:formId";
  };
  "features/embed/page.tsx": {
    id: "features/embed/page";
    page: "/dashboard/embed/:formId";
  };
  "features/form-settings/page.tsx": {
    id: "features/form-settings/page";
    page: "/dashboard/settings/:formId";
  };
  "features/edit-form/page.tsx": {
    id: "features/edit-form/page";
    page: "/:formId/edit";
  };
  "features/preview/page.tsx": {
    id: "features/preview/page";
    page: "/preview";
  };
  "features/form/route.tsx": {
    id: "features/form/route";
    page: "/:formId" | "/:formId/verify";
  };
  "features/form/page.tsx": {
    id: "features/form/page";
    page: "/:formId";
  };
  "features/form/verify-page.tsx": {
    id: "features/form/verify-page";
    page: "/:formId/verify";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "features/marketing/page": typeof import("./app/features/marketing/page.tsx");
  "features/auth/page": typeof import("./app/features/auth/page.tsx");
  "features/auth/protected": typeof import("./app/features/auth/protected.tsx");
  "features/dashboard/route": typeof import("./app/features/dashboard/route.tsx");
  "features/dashboard/page": typeof import("./app/features/dashboard/page.tsx");
  "features/workspace/route": typeof import("./app/features/workspace/route.tsx");
  "features/workspace/page": typeof import("./app/features/workspace/page.tsx");
  "features/custom-domain/route": typeof import("./app/features/custom-domain/route.tsx");
  "features/custom-domain/page": typeof import("./app/features/custom-domain/page.tsx");
  "features/form-manage/route": typeof import("./app/features/form-manage/route.tsx");
  "features/submissions/page": typeof import("./app/features/submissions/page.tsx");
  "features/analytics/page": typeof import("./app/features/analytics/page.tsx");
  "features/integrations/page": typeof import("./app/features/integrations/page.tsx");
  "features/embed/page": typeof import("./app/features/embed/page.tsx");
  "features/form-settings/page": typeof import("./app/features/form-settings/page.tsx");
  "features/edit-form/page": typeof import("./app/features/edit-form/page.tsx");
  "features/preview/page": typeof import("./app/features/preview/page.tsx");
  "features/form/route": typeof import("./app/features/form/route.tsx");
  "features/form/page": typeof import("./app/features/form/page.tsx");
  "features/form/verify-page": typeof import("./app/features/form/verify-page.tsx");
};